### ISSUE TITLE
Game freezes upon choosing character

### ISSUE THREAD

**Issue by ClassixX** [daviscook477/BaseMod#133] opened 2018-09-29 16:57 UTC
The title is the name of the game, it freezes during the fade out after confirming the character. The launchher reports it as follows:

Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: java.lang.NoSuchFieldError: enabledMods
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:133)
Caused by: java.lang.NoSuchFieldError: enabledMods
	at basemod.patches.com.megacrit.cardcrawl.ui.panels.TopPanel.TopPanelPatches$SetPlayerNamePatch.Postfix(TopPanelPatches.java:207)
	at com.megacrit.cardcrawl.ui.panels.TopPanel.setPlayerName(TopPanel.java:211)
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.<init>(AbstractDungeon.java:337)
	at com.megacrit.cardcrawl.dungeons.Exordium.<init>(Exordium.java:50)
	at com.megacrit.cardcrawl.core.CardCrawlGame.getDungeon(CardCrawlGame.java:1370)
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:883)
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:466)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)

**Comment by kiooeht** [comment] 2018-09-29 17:05
Duplicate of #132 
Make sure you have the latest version of both BaseMod and Slay the Spire.

**Closed by kiooeht** 2018-09-29 17:05 UTC
